const constants = {
  FETCH_ADMIN_REQUEST: "FETCH_ADMIN_REQUEST",
  FETCH_ADMIN_SUCCESS: "FETCH_ADMIN_SUCCESS",
  ADD_USER_REQUEST: "ADD_USER_REQUEST",
  ADD_USER_RESPONSE: "ADD_USER_RESPONSE",
  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_RESPONSE: "UPDATE_USER_RESPONSE",
  DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
  DELETE_USER_RESPONSE: "DELETE_USER_RESPONSE",
  GET_USER_REQUEST:"GET_USER_REQUEST",
  GET_USER_SUCCESS:"GET_USER_SUCCESS",
  USER_REGISTER_REQUEST:"USER_REGISTER_REQUEST",
  USER_REGISTER_RESPONSE:"USER_REGISTER_RESPONSE",
  USER_REGISTER_FAILED:"USER_REGISTER_FAILED",
  USER_LOGIN_REQUEST:"USER_LOGIN_REQUEST",
  USER_LOGIN_RESPONSE:"USER_LOGIN_RESPONSE",
  USER_LOGIN_FAIL:"USER_LOGIN_FAIL",
  USER_LOGOUT_REQUEST:"USER_LOGOUT_REQUEST"
};

export default constants;
